"""empty message

Revision ID: b5f316dacf81
Revises: 
Create Date: 2018-06-14 16:06:00.046311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f316dacf81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shelter_shelter_id'), 'shelter', ['shelter_id'], unique=False)
    op.drop_constraint('shelter_ref_id_key', 'shelter', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('shelter_ref_id_key', 'shelter', ['ref_id'])
    op.drop_index(op.f('ix_shelter_shelter_id'), table_name='shelter')
    # ### end Alembic commands ###
